services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: vaccines-keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin_p

    volumes:
      - keycloak_data:/opt/keycloak/data

  postgres:
    image: postgres:16-alpine
    container_name: vaccines-postgres
    environment:
      POSTGRES_DB: vaccines
      POSTGRES_USER: vaccines
      POSTGRES_PASSWORD: vaccines
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U vaccines" ]
      interval: 5s
      timeout: 5s
      retries: 5

  vaccines-api:
    build: .
    container_name: vaccines-api
    env_file:
      - .env.docker
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  keycloak_data: