"""initial schema

Revision ID: 54141adee39e
Revises: 
Create Date: 2026-09-17 02:44:44.346545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54141adee39e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keycloak_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('keycloak_id', name=op.f('uq_users_keycloak_id'))
    )
    op.create_table('vaccines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('disease', sa.String(), nullable=False),
    sa.Column('vaccine_name', sa.String(), nullable=False),
    sa.Column('dose_number', sa.String(), nullable=False),
    sa.Column('vaccination_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('type_vaccine', sa.String(), nullable=False),
    sa.Column('lot', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('clinic', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vaccines_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vaccines'))
    )
    with op.batch_alter_table('vaccines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vaccines_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vaccines_user_id'))

    op.drop_table('vaccines')
    op.drop_table('users')
    # ### end Alembic commands ###
